// Ascendancy override üreticisi (TEK SEFERLİK yazım aracı).
// _asc-lines.json'daki SIRA ile birebir eşleşen TR[] dizisini zip'ler -> ascendancies.tr.json
// Anahtarlar _asc-lines.json'dan ALINIR (tam eşleşme garantisi). Çeviri = doğal TR, proje talimatları terimleri.
const fs = require('fs')
const path = require('path')
const keys = require('./_asc-lines.json').map((x) => x[0])
const TR = [
  /*1*/ "Kendin kullandığın her ikinci Çarpma Yeteneği Atadan Güçlendirilir",
  /*2*/ "%15 daha fazla Azami Can",
  /*3*/ "Kuşanılmış Gövde Zırhından %50 daha fazla Zırh",
  /*4*/ "Küçük Pasif Yeteneklerin etkisi %50 artar",
  /*5*/ "Çarpma Etki Alanı",
  /*6*/ "Çarpma Yeteneklerinin Etki Alanı %8 artar",
  /*7*/ "Kendin kullandığın Çarpma Yeteneklerinin ek bir Artçı Sarsıntı yaratma %25 şansı olur",
  /*8*/ "Saniyede azami Canın %0.5'ini yenile",
  /*9*/ "Ezici Darbeler",
  /*10*/ "Ağır Sersemletilmiş Düşmanlara %25 daha fazla Hasar",
  /*11*/ "Vuruşların Ezici Darbedir",
  /*12*/ "Kendin kullandığın, Yarık yaratmayan her üçüncü Çarpma Yeteneği, ilk alanın önünde ve her iki yanında 3 ek Artçı Sarsıntı yaratır",
  /*13*/ "20 Envanter Yuvası ekleyen bir Sandık taşırsın",
  /*14*/ "Her saniye bir Yeşim yığını kazan",
  /*15*/ "Beceri verir: Encase in Jade",
  /*16*/ "Blok Şansı",
  /*17*/ "Kuşanılmış Kalkanın kendi değeri yerine Kalkandan %35 Temel Blok Şansı kazan",
  /*18*/ "Uyguladığın Tamamen Kırılmış Zırh, bunun yerine Vuruşlardan Alınan tüm Hasarı artırır",
  /*19*/ "Düşman Zırhını 0'ın altına Kırabilirsin",
  /*20*/ "Totem Canı",
  /*21*/ "%20 artan Totem Canı",
  /*22*/ "Çağrılan Totem azami sayısı +1",
  /*23*/ "Bir Totem Çağırdığında Ancestral Spirits'i tetikle",
  /*24*/ "Vuruşlardan gelen Hasarın %20'si, senden önce en yakın Totemin Canından alınır",
  /*25*/ "Savaş Çığlıkları Cesetleri patlatır ve Canlarının %25'i kadar Fiziksel Hasar verir",
  /*26*/ "Savaş Çığlığı Bekleme Sürelerini yok say",
  /*27*/ "Bloklanan Vuruşlardan gelen hasarın %20'sini alırsın",
  /*28*/ "Azami Blok şansı %75'tir",
  /*29*/ "Gövde Zırhı şunu verir: sana karşı Vuruşların Kritik Hasar Bonusu %100 azalır",
  /*30*/ "Gövde Zırhı şunu verir: saniyede azami Canın %3'ünü yenile",
  /*31*/ "Yalnızca Normal bir Gövde Zırhı kullanabilirsin",
  /*32*/ "Bağlı ve dağıtılmış her Kayda Değer Pasif Yetenek için +200 Zırh",
  /*33*/ "Gövde Zırhı şunu verir: Vuruşlardan gelen Fiziksel Hasarın %25'i Ateş Hasarı olarak alınır",
  /*34*/ "Gövde Zırhı şunu verir: Zırhın +%50'si Element Hasarına da uygulanır",
  /*35*/ "Gövde Zırhı şunu verir: Glory üretimi %60 artar",
  /*36*/ "Gövde Zırhı şunu verir: Diken hasarı %100 artar",
  /*37*/ "Demir Ocağının Harareti",
  /*38*/ "Utula'ya Haraç",
  /*39*/ "Gövde Zırhı şunu verir: Ruh %30 artar",
  /*40*/ "Gövde Zırhı şunu verir: Hasar Veren Rahatsızlıklardan etkilenmezsin",
  /*41*/ "Beceri verir: Manifest Weapon",
  /*42*/ "Azami Ateş Direncine etki eden Değiştiriciler, Azami Soğuk ve Yıldırım Direnci de verir",
  /*43*/ "Gövde Zırhı şunu verir: Güç %20 artar",
  /*44*/ "Ateş Direncine etki eden Değiştiriciler, değerlerinin %50'si kadar Soğuk ve Yıldırım Direnci de verir",
  /*45*/ "Örse Karşı",
  /*46*/ "Gövde Zırhı şunu verir: azami Can %15 artar",
  /*47*/ "Gövde Zırhı şunu verir: Ateş Direnci +%75",
  /*48*/ "Kitava'ya Adanmışlık",
  /*49*/ "Gövde Zırhı şunu verir: Zırhın +%100'ü Kaos Hasarına da uygulanır",
  /*50*/ "Yeteneklerin için Çılgınlık Şarjı tüketmenin faydalarının iki katına çıkma %50 şansı olur",
  /*51*/ "Düşmanlardaki bir İşareti Tükettiğinde onlara 10 Kritik Zafiyet uygula",
  /*52*/ "İşaret Etkisi",
  /*53*/ "İşaret Yeteneklerinin Etkisi %12 artar",
  /*54*/ "Mermiler, hareketlerinin ilk 3.5 metresinde hedeflere %20 daha fazla Vuruş hasarı verir; kat edilen mesafeyle azalarak 7 metre sonra %0'a iner",
  /*55*/ "Mermiler, hareketlerinin ilk 3.5 metresinde hedeflere %0 daha fazla Vuruş hasarı verir; kat edilen mesafeyle artarak 7 metre sonra %20'ye çıkar",
  /*56*/ "Kazanılan Can Şişesi Şarjı %20 artar",
  /*57*/ "Kaçınma Derecesinin %50'si, Element Hasarı azaltması da verir",
  /*58*/ "1 Pasif Yetenek Puanı verir",
  /*59*/ "Büyücünün Yolu",
  /*60*/ "Büyücünün başlangıç noktasından Pasif Yetenekler dağıtabilirsin",
  /*61*/ "4 Pasif Yetenek Puanı verir",
  /*62*/ "Zehir Etkisi",
  /*63*/ "Uyguladığın Zehrin Büyüklüğü %12 artar",
  /*64*/ "Hızın Yavaşlatmalardan etkilenmez",
  /*65*/ "Hedeflerin aynı anda etkilenebileceği Zehir sayını iki katına çıkar",
  /*66*/ "Rezerve Edilmemiş Can dolduğunda Can Şişesi Etkileri kaldırılmaz",
  /*67*/ "Can Şişesi Etkileri sıraya girmez",
  /*68*/ "Nitelik Pasif Yetenekleri bunun yerine %5 artan Hasar verebilir",
  /*69*/ "Nitelik Pasif Yetenekleri bunun yerine %5 artan Zırh, Kaçınma ve Enerji Kalkanı verebilir",
  /*70*/ "Nitelik Pasif Yetenekleri bunun yerine %5 artan Maliyet Verimliliği verebilir",
  /*71*/ "Savaşçının Yolu",
  /*72*/ "Savaşçının başlangıç noktasından Pasif Yetenekler dağıtabilirsin",
  /*73*/ "Hareket hâlindeyken Yetenek kullanmanın Hareket Hızı Cezası %30 daha az",
  /*74*/ "%3 artan azami Can",
  /*75*/ "Infernal Flame azamiye ulaştığında azami Can ve Enerji Kalkanı kadar Ateş Hasarı alırsın",
  /*76*/ "Beceri verir: Summon Infernal Hound",
  /*77*/ "Canın %25'ini Rezerve eder",
  /*78*/ "Her 8 Azami Can için Azami Enerji Kalkanı +1",
  /*79*/ "Bir Kritik Vuruş yaptığında Tutuşursun ve saniyede azami Can ve Enerji Kalkanının %15'i kadar Ateş Hasarı alırsın",
  /*80*/ "Her 6 Azami Can için Azami Mana +1",
  /*81*/ "Hizmetkârların azami Canı %12 artar",
  /*82*/ "Her 25 Azami Can için Azami Ruh +1",
  /*83*/ "Demonflame'in azami sınırı yoktur",
  /*84*/ "Yetenekler, Temel Mana Maliyetine eşit bir Temel Can Maliyeti kazanır",
  /*85*/ "Beceri verir: Life Remnants",
  /*86*/ "Büyü Hasarının %20'si Can olarak Emilir",
  /*87*/ "Element Hasarı, Kanama Büyüklüğüne de katkı sağlar",
  /*88*/ "Lanetli hedeflere uyguladığın Kanama Şiddetlenir",
  /*89*/ "Eti Parçala",
  /*90*/ "Büyüler için Temel Kritik Vuruş Şansı %15'tir",
  /*91*/ "Etin Fısıltıları",
  /*92*/ "Senin Lanetlediğin hedeflerin Can Yenilenme Hızı %100 azalır",
  /*93*/ "Senin Lanetlediğin hedeflerin Canının en az %15'i Rezerve edilir",
  /*94*/ "Lanet Etkisi",
  /*95*/ "Kuşanılmış Gövde Zırhındaki Eşya Enerji Kalkanının %100'üne eşit ek azami Can kazan",
  /*96*/ "Kazanılan Can Şişesi Şarjı %15 artar",
  /*97*/ "Mevcut her 50 Can için Kritik Hasar Bonusu %1 artar",
  /*98*/ "Vuruşlardan gelen Can Kaybının %25'i önlenir, sonra o kadar Can bunun yerine 4 saniyeye yayılarak kaybedilir",
  /*99*/ "Emilen Can miktarı %12 artar",
  /*100*/ "Kritik Vuruşta Kanama uygulama %15 şansı",
  /*101*/ "Şişeler Can yenilemez",
  /*102*/ "Harcanan her %2 Can için 1 Can Şişesi Şarjı kazan",
  /*103*/ "Bir Can Şişesi tam Şarjdayken bir Düşmana Vurduğunda, Şarjlarının %40'ı tüketilir",
  /*104*/ "Bu şekilde tüketilen her Şarj için 5 saniye boyunca hasarın %1'i kadar Fiziksel hasar kazan",
  /*105*/ "Uyguladığın Lanetlerin Süresi sonsuzdur",
  /*106*/ "Büyüler, %40 daha fazla Hasar verebiliyorsa bir Güç Şarjı tüketir",
  /*107*/ "Her 100 azami Mana için, verdiğin Unholy Might Güçlendirmelerinin Büyüklüğü %4 artar",
  /*108*/ "Güç Şarjı Tüketildiyse Enerji Kalkanı",
  /*109*/ "Yakın zamanda bir Güç Şarjı tükettiysen azami Enerji Kalkanı %30 artar",
  /*110*/ "Lanet Alanı",
  /*111*/ "Phylactery'ye Eşsiz olmayan Temel bir Mücevher takabilirsin",
  /*112*/ "Takılı Mücevherden kazanılan bonusların Etkisi %100 artar",
  /*113*/ "Enerji Kalkanın yoksa Yeteneklerin Mana Maliyeti %50 daha fazla",
  /*114*/ "Ruhu Patlat",
  /*115*/ "Senin ya da Huzurundaki Müttefiklerin öldürdüğü Lanetli Düşmanların, azami Canlarının çeyreği kadar Kaos hasarı vererek patlama %33 şansı olur",
  /*116*/ "Düşük Manada değilken, sen ve Huzurundaki Müttefiklerin Unholy Might'a sahip olur",
  /*117*/ "Enerji Kalkanın varken Canın değişemez",
  /*118*/ "Alınan Hasarın %10'u Enerji Kalkanını atlar",
  /*119*/ "Saniyede azami Canın %6'sına eşit Mana yenile",
  /*120*/ "Enerji Kalkanı feda etmek Yeniden Dolumu kesmez",
  /*121*/ "Bu Feda'nın tam yapıldığı Büyüler %30 daha fazla Hasar verir",
  /*122*/ "Hedefler aynı anda iki Şokundan etkilenebilir",
  /*123*/ "Uyguladığın Şokun Büyüklüğü %25 daha az",
  /*124*/ "Büyülerle Kritik Vuruşta Elemental Storm'u tetikle",
  /*125*/ "Vuruşlardan gelen tüm Hasar, Üşüme Büyüklüğüne katkı sağlar",
  /*126*/ "Hasarın %20'si Candan önce Manadan alınır",
  /*127*/ "Eksik her yüzde on Mana için, üzerindeki Arcane Surge Etkisi %20 artar",
  /*128*/ "Vuruşlardan gelen tüm Hasar, Şok Şansına katkı sağlar",
  /*129*/ "Bir Elemental Infusion topladığında, farklı bir Elemental Infusion daha kazan",
  /*130*/ "Hedefler aynı anda iki Üşümenden etkilenebilir",
  /*131*/ "Üşümelerin hedefleri en fazla %35'e kadar Yavaşlatabilir",
  /*132*/ "Uyguladığın Üşümenin Büyüklüğü %25 daha az",
  /*133*/ "Sands of Time verir",
  /*134*/ "Ara Sıra",
  /*135*/ "Kademelenebilir Büyülerin Yankılanma %20 şansı olur",
  /*136*/ "Tekrarlanabilir Büyülerin Tekrarlama %20 şansı olur",
  /*137*/ "Kumdaki Ayak İzleri",
  /*138*/ "Yavaşlatma Etkisi",
  /*139*/ "Uyguladığın Zayıflatmaların Yavaşlatma Büyüklüğü %6 artar",
  /*140*/ "Bir Düşman Vuruşundan Hasar aldıktan 4 saniye sonra, o Vuruşun Hasarının %30'una eşit Hasar alırsın",
  /*141*/ "Yetenek Hızı ve Etki Alanı",
  /*142*/ "Anın Zirvesi",
  /*143*/ "Huzurundaki Düşmanlar %20 Yavaşlatılır",
  /*144*/ "Etki Alanı",
  /*145*/ "Element Hasarının %100'ü Candan önce Manadan alınır",
  /*146*/ "Beceri verir: Kelari, the Tainted Sands",
  /*147*/ "Bir Asa kuşanırken bir Focus takabilirsin",
  /*148*/ "Kuşanılmış Focus'tan kazanılan bonuslar %50 azalır",
  /*149*/ "Beceri verir: Navira, the Last Mirage",
  /*150*/ "Beceri verir: Ruzhan, the Blazing Sword",
  /*151*/ "Eşsiz olmayan Time-Lost Mücevherlerin yarıçapı %40 artar",
  /*152*/ "Dördüncü Öğreti",
  /*153*/ "Temel Enerji Kalkanı Yeniden Dolum gecikmesi -1 saniye",
  /*154*/ "Mevcut Enerji Kalkanının %60'ı şunun için Zırhına eklenir:",
  /*155*/ "Zırhtan gelen Fiziksel Hasar Azaltmanın belirlenmesi",
  /*156*/ "Can Emme, Fiziksel hasarın yanı sıra Element hasarına göre de yeniler",
  /*157*/ "Şişelerden Can ve Mana Yenilemesi %15 artar",
  /*158*/ "Bir Şarj Tükettiğinde, 3 Lightning Surge kazanmak için Elemental Surge'ü tetikle",
  /*159*/ "Saldırılarla Vurma Şansı %100'ü aşabilir",
  /*160*/ "Saldırılarla Vurma şansının fazlasının %25'ine eşit ek Kritik Vuruş Şansı kazan",
  /*161*/ "Öldürmeye Hazır",
  /*162*/ "Huzurunda Açık Zafiyeti olan bir düşman varken Hareket Hızı %20 artar",
  /*163*/ "Huzurunda Açık Zafiyeti olan bir düşman varken Yetenek Hızı %40 artar",
  /*164*/ "Silahlarını kullanan Saldırılar şuna eşit Eklenmiş Fiziksel Hasar kazanır:",
  /*165*/ "Silahtaki Doğruluk Derecesinin %25'i",
  /*166*/ "Bir Şarj Tükettiğinde, 2 Fire Surge kazanmak için Elemental Surge'ü tetikle",
  /*167*/ "Bir Şarj Tükettiğinde, 2 Cold Surge kazanmak için Elemental Surge'ü tetikle",
  /*168*/ "Elemental Surge tetiklemekten 1 daha az Lightning Surge kazan",
  /*169*/ "Can Şişeleri Mana da yeniler",
  /*170*/ "Mana Şişeleri Can da yeniler",
  /*171*/ "Nadir ve Eşsiz düşmanlara karşı Zafiyetleri açığa çıkar",
  /*172*/ "Açık Zafiyeti olan düşmanlara %50 daha fazla hasar",
  /*173*/ "Kuşanılmış Kask, Eldiven ve Botlardan gelen Kaçınma Derecesi iki katına çıkar",
  /*174*/ "Kuşanılmış Gövde Zırhından gelen Kaçınma Derecesi yarıya iner",
  /*175*/ "Catha'nın Dengesi",
  /*176*/ "Yoldaşlar, ana el Silahının hasarının %60'ına eşit eklenmiş Saldırı hasarı kazanır",
  /*177*/ "Mhacha'nın Armağanı",
  /*178*/ "Sıyrılmak en fazla 3 Owl Feather harcayabilir ve Primal Bounty'ye %100 daha fazla",
  /*179*/ "harcanan her ek Feather için Güçlendirme etkisi",
  /*180*/ "Owl Feather'ları %50 daha hızlı kazan",
  /*181*/ "Paylaşılan Yoldaş Hasarı",
  /*182*/ "Yoldaşlar %10 artan Hasar verir",
  /*183*/ "Yoldaşın Huzurundayken %10 artan Hasar",
  /*184*/ "Mórrigan'ın Rehberliği",
  /*185*/ "Geyikler her sıçrayışta %20 daha fazla hasar verir",
  /*186*/ "Geyiklerin her sıçrayışta Şok Büyüklüğü %20 daha fazla",
  /*187*/ "Bear Spirit, Embrace of the Wild kazanır",
  /*188*/ "Vivid Stag'ler düşmanlara doğru sıçrar",
  /*189*/ "Owl Feather ile Güçlendirilmiş Yeteneklerin Merkez Mermisi, bir Soaring Ground izi bırakır",
  /*190*/ "Doğal Düzen",
  /*191*/ "Tame Beast, Eşsiz Canavarları yakalayabilir",
  /*192*/ "Çağrılmış en fazla bir Eşsiz Evcil Canavarın olabilir",
  /*193*/ "Eşsiz Evcil Canavarların hareket hızı %30 artar",
  /*194*/ "Eşsiz Evcil Canavarlar, her 20 saniyede değişen rastgele Azmeri Ruhları tarafından Ele Geçirilir",
  /*195*/ "Hareket ettiğin her 10 metre için bir Vivid Wisp kazan, en fazla 3",
  /*196*/ "Saldırdığında Vivid Stampede'i tetiklemek için tüm Vivid Wisp'leri harca",
  /*197*/ "Yoldaş Canı ve Alanı",
  /*198*/ "Yoldaşların Etki Alanı %10 artar",
  /*199*/ "Yoldaşların azami Canı %15 artar",
  /*200*/ "Her 4 saniyede bir Primal Owl Feather kazan, en fazla 3",
  /*201*/ "Primal Bounty'yi tetiklemek için Sıyrıldığında bir Owl Feather harca",
  /*202*/ "Teçhizatındaki her Idol için Yoldaşlar %10 artan hasar verir",
  /*203*/ "Teçhizatındaki her Idol için Yeteneklerin Rezervasyon Verimliliği %2 artar",
  /*204*/ "Kuşanılmış Yüzük ve Kolyelerden kazanılan bonuslar %25 artar",
  /*205*/ "Azaltılmış Dirençler",
  /*206*/ "Yetersiz şarjı olan Tılsımları tetiklemek için bunun yerine azami Mananın %25'ini tüketebilirsin",
  /*207*/ "Fısıltılar Buyurdukça",
  /*208*/ "Blood Boil'den etkilenen Düşmanlara %15 daha fazla Hasar",
  /*209*/ "Azaltılmış Ruh",
  /*210*/ "Can Yenileme hızı %10 artar",
  /*211*/ "Azaltılmış Mana",
  /*212*/ "Eksik her %5 Rezerve Edilmemiş Can için Can Yenileme hızı %10 artar",
  /*213*/ "Yerleştirdiğin Totemler Embankment Aurası verir",
  /*214*/ "Sancaklar saniyede 5 Glory kazanır",
  /*215*/ "Yerleştirebileceğin Sancak sayısında bir Sınır yoktur",
  /*216*/ "Totem Hasarı",
  /*217*/ "%20 artan Totem Hasarı",
  /*218*/ "Kalıcı Güçlendirmelerin Rezervasyonu %50 daha az",
  /*219*/ "Zırh ve Kaçınma",
  /*220*/ "Huzur Alanı",
  /*221*/ "Hafif Kal, Siper Kullan",
  /*222*/ "Zırhın %200'ü ile Savun",
  /*223*/ "Düşmanların sana karşı Mesafeye dayalı bir Doğruluk Cezası olur",
  /*224*/ "Azami Kaçınma Şansı %50'dir",
  /*225*/ "Azami Fiziksel Hasar Azaltması %50'dir",
  /*226*/ "Totemlerin kullandığı Yeteneklerin Yetenek Hızı %30 daha fazla",
  /*227*/ "Totemler yalnızca sen bir Saldırı Mermisi attığında Yetenek kullanır",
  /*228*/ "Sancak Alanı",
  /*229*/ "Sancak Yeteneklerinin Etki Alanı %16 artar",
  /*230*/ "O Teçhizatı Parlat",
  /*231*/ "Kaçınma Derecesinin %100'ünü ek Rahatsızlık Eşiği olarak kazan",
  /*232*/ "Tam İstediğimiz Yerde",
  /*233*/ "Düşmanların, Azami Canlarının %30'una eşit Azami Konsantrasyonu olur",
  /*234*/ "Düşmanlar son 5 saniyede Konsantrasyon kaybetmediyse her saniye Konsantrasyonun %10'unu geri kazanır",
  /*235*/ "Sorcery Ward'ın Bariyeri, Vuruşlardan gelen Fiziksel ve Kaos Hasarını da alabilir",
  /*236*/ "100 Pasif Yetenek Puanı, Silah Seti Yetenek Puanına dönüşür",
  /*237*/ "Yargıç, Jüri ve Cellat",
  /*238*/ "azami Canlarının o kadarı Fiziksel Hasar olarak",
  /*239*/ "Şans, Hortlaklara ve İblislere karşı iki katına çıkar",
  /*240*/ "Düşük Candaki Düşmanlara karşı Vuruşlarla Hasar %35 artar",
  /*241*/ "Düşmanlara, eksik Konsantrasyonlarına göre %40'a kadar daha fazla Hasar ver",
  /*242*/ "Azaltılmış Nitelik Gereksinimleri",
  /*243*/ "Teçhizat ve Yetenek Taşlarının Nitelik Gereksinimleri %4 azalır",
  /*244*/ "Taş Kalitesi, Takılı Yeteneklere ek bir etki verir",
  /*245*/ "En çok sayıda olan her Takılı Destek Taşı rengi için şunu kazan:",
  /*246*/ "•Kırmızı: Sana karşı Vuruşların Kritik Hasar Bonusu olmaz",
  /*247*/ "•Mavi: Yeteneklerin maliyeti %30 daha az",
  /*248*/ "•Yeşil: Hareket hâlindeyken Yetenek kullanmanın Hareket Hızı Cezası %40 daha az",
  /*249*/ "Güç gereksinimi olan tüm Yeteneklerin Seviyesi +2",
  /*250*/ "Takılı her 3 Mavi Destek Taşı için Azami Soğuk Direnci +%1",
  /*251*/ "Takılı her 3 Kırmızı Destek Taşı için Azami Ateş Direnci +%1",
  /*252*/ "Takılı her 3 Yeşil Destek Taşı için Azami Yıldırım Direnci +%1",
  /*253*/ "Zekâ gereksinimi olan tüm Yeteneklerin Seviyesi +2",
  /*254*/ "Taşların Nitelik Gereksinimleri, en yüksek Niteliğinle karşılanabilir",
  /*255*/ "Bağlı her Kırmızı Destek Taşı için Yetenekler %20 artan Hasar verir",
  /*256*/ "Bağlı her Yeşil Destek Taşı için Yeteneklerin Yetenek Hızı %6 artar",
  /*257*/ "Bağlı her Mavi Destek Taşı için Yeteneklerin Kritik Vuruş Şansı %20 artar",
  /*258*/ "Niteliklerden kazanılan doğal bonuslar iki katına çıkar",
  /*259*/ "Çeviklik gereksinimi olan tüm Yeteneklerin Seviyesi +2",
  /*260*/ "Vücuduna Rune dövmesi yapabilir ve şunları kazanırsın:",
  /*261*/ "ek, yalnızca Rune yuvaları:",
  /*262*/ "• 1 Kask yuvası",
  /*263*/ "• 2 Gövde Zırhı yuvası",
  /*264*/ "• 1 Eldiven yuvası",
  /*265*/ "• 1 Bot yuvası",
  /*266*/ "Taşyumruk Yolu",
  /*267*/ "Kuşandığın Eldivenlerin Taban Türü, kuşanılıyken Fists of Stone'a dönüşür ve",
  /*268*/ "Belirgin Değiştiricileri, ilgili daha güçlü Değiştiricilere dönüşür",
  /*269*/ "Eldiven kuşanmak için Nitelik Gereksinimlerini yok say",
  /*270*/ "Yetenek kullanırken harcanan her Combo için mevcut Enerji Kalkanı Yeniden Dolum gecikmesi -0.2 saniye",
  /*271*/ "Dağın Yolu",
  /*272*/ "Bir düşmanı Hareketsiz bıraktığında, düşman Gücü başına %100 Aşma şansıyla Mountain's Teachings kazan, en fazla 30'a kadar",
  /*273*/ "Vurulduğunda ya da Mountain's Teachings'ten faydalanan bir Saldırı kullandığında veya Sürdürdüğünde bir Mountain's Teaching kaybedersin",
  /*274*/ "Kaçınma ve Enerji Kalkanı",
  /*275*/ "Yetenekler, Silah Setinden bağımsız olarak Combo oluşturabilir ve koruyabilir",
  /*276*/ "Tüm Saldırı Vuruşlarından Combo kazan",
  /*277*/ "Ben Gök Gürültüsüyüm...",
  /*278*/ "Hasarın %10'unu Ekstra Yıldırım Hasarı olarak kazan",
  /*279*/ "Düşmanları Şoklarken Şoklu Zemin oluşturma %25 şansı",
  /*280*/ "Kuşanılmış Gövde Zırhındaki her 8 Eşya Enerji Kalkanı için Ruh +1",
  /*281*/ "Kuşanılmış Gövde Zırhındaki her 20 Kaçınma Derecesi için Ruh +1",
  /*282*/ "Teçhizattan Ruh kazanamazsın",
  /*283*/ "İnanç Bir Tercihtir",
  /*284*/ "Şok Etkisi",
  /*285*/ "Uyguladığın Şokun Büyüklüğü %15 artar",
  /*286*/ "Ben Tipiyim...",
  /*287*/ "Hasarın %10'unu Ekstra Soğuk Hasarı olarak kazan",
  /*288*/ "Düşmanları Dondurduğunda Üşütücü Zemin oluştur",
  /*289*/ "Üşüme Etkisi",
  /*290*/ "Uyguladığın Üşümenin Büyüklüğü %15 artar",
  /*291*/ "...ve Onları Rüzgâra Savur",
  /*292*/ "Yakın Dövüş Kritik Vuruşunda Elemental Expression'ı tetikle",
  /*293*/ "Ruh Hiç Tükenmez",
  /*294*/ "Meta Yeteneklerin Rezervasyon Verimliliği %50 artar",
  /*295*/ "...ve Öfkeleneceğim",
  /*296*/ "...ve Beni Zarardan Koru",
  /*297*/ "Zırhtan gelen Fiziksel Hasar Azaltması, birleşik Zırh ve Kaçınma Derecene dayanır",
  /*298*/ "Oluşturduğun Remnant'ların etkisi %50 artar",
  /*299*/ "Belirdiğin tüm Flames of Chayula Mor olur",
  /*300*/ "Volatility'den Hasar almazsın",
  /*301*/ "Emme, Fiziksel Hasarın yanı sıra Kaos Hasarına göre de yeniler",
  /*302*/ "Kaos Olarak Hasar",
  /*303*/ "Hasarın %4'ünü Ekstra Kaos Hasarı olarak kazan",
  /*304*/ "Belirdiğin tüm Flames of Chayula Mavi olur",
  /*305*/ "Boşluğun Kavrayışı",
  /*306*/ "Emilen Can miktarı %11 artar",
  /*307*/ "Karanlığı Kucakla",
  /*308*/ "Hiç Ruhun yoktur",
  /*309*/ "Temel Azami Karanlık 100'dür",
  /*310*/ "Alınan Hasar, Candan veya Enerji Kalkanından alınmadan önce Karanlıktan Rezerve edilir",
  /*311*/ "Karanlık Rezervasyonu 5 saniye sürer",
  /*312*/ "Beceri verir: Into the Breach",
  /*313*/ "Belirdiğin tüm Flames of Chayula Kırmızı olur",
  /*314*/ "Kaos Direnci iki katına çıkar",
  /*315*/ "Görünmeyen Yol",
  /*316*/ "Gidilmemiş Yolları Yürü",
  /*317*/ "Totem Büyü ve Saldırı Hızı",
  /*318*/ "Totemlerin yaptığı Büyülerin Büyü Hızı %5 artar",
  /*319*/ "Totemlerin kullandığı Saldırıların Saldırı Hızı %5 artar",
  /*320*/ "Can ve Mana Yenilenme Hızı",
  /*321*/ "Can Yenilenme hızı %8 artar",
  /*322*/ "Sana Karşı Kritik Hasar Bonusu",
  /*323*/ "Sana karşı Vuruşların Kritik Hasar Bonusu %12 azalır",
  /*324*/ "İçsel Uyum",
  /*325*/ "Mevcut Manan mevcut Canından yüksekse, Vuruş hasarı Candan önce Manadan alınır",
  /*326*/ "%15 daha az azami Can",
  /*327*/ "Dağıtılmış Kilittaşı Pasif Yeteneklerin Orta Yarıçapındaki Kilittaşı olmayan Pasif Yetenekler, ağacına bağlı olmadan dağıtılabilir",
  /*328*/ "Daha Küçük Zarar",
  /*329*/ "Düşmanların sana karşı Kritik Vuruş Şansı Şanssızdır",
  /*330*/ "Sana Vuran Düşmanların Hasarı Şanssızdır",
  /*331*/ "Totemler, Canları 0'a indikten 6 saniye sonra ölür",
  /*332*/ "Şişelerden Can ve Mana Yenilemesi %12 artar",
  /*333*/ "Boş her Tılsım yuvan için Ruh +40",
  /*334*/ "Kıyametin Getiricisi",
  /*335*/ "Mana Yenilenme Hızındaki artış ve azalışlar, Öfke Yenilenme Hızına da uygulanır",
  /*336*/ "Yeteneklerin Öfke maliyeti +5",
  /*337*/ "Azami Öfke",
  /*338*/ "Maji'nin Bilgeliği",
  /*339*/ "Rune ve Idol'lerdeki Bonded değiştiricilerin faydalarını kazan",
  /*340*/ "Her 2 Öfke ayrıca %1 daha fazla Büyü hasarı verir",
  /*341*/ "Alınan Element Hasarı %10 daha az",
  /*342*/ "Aldığın her Vuruşun en yüksek Element Hasar Türüne uyum sağla",
  /*343*/ "Eşleşen her Adaptasyon için, her Element Hasar Türünden alınan Hasar %10 daha az",
  /*344*/ "Adaptasyonların süresi 5 saniyedir",
  /*345*/ "Adaptasyon Etkisini iki katına çıkar",
  /*346*/ "Mevsimlerin Dönüşü",
  /*347*/ "Huzurundaki Düşmanlarda Exposure olur",
  /*348*/ "Hasarın %10'unu rastgele bir Elementten Ekstra Hasar olarak kazan"
]
if (TR.length !== keys.length) {
  console.error('UYUMSUZ: keys', keys.length, 'TR', TR.length); process.exit(1)
}
const out = { _note: 'ELLE tam-cümle TR çevirileri (ascendancy node adları + stat satırları). Anahtar = tam İngilizce satır/ad. build-ascendancies.ts trName + trStat içinde satır bazlı ÖNCE okur. Rebuild EZMEZ; elle düzenlenebilir. _ ile başlayanlar yok sayılır.' }
keys.forEach((k, i) => { out[k] = TR[i] })
fs.writeFileSync(path.join(__dirname, 'ascendancies.tr.json'), JSON.stringify(out, null, 2) + '\n', 'utf-8')
console.log('Yazıldı: ascendancies.tr.json,', keys.length, 'kayıt')
